/**
 * @file    svc_http_page.c
 * @brief   回放页面(一整段常量 HTML/CSS/JS, **不带任何前端构建步骤**)
 *
 * 【模块职责】把"板子自带的那个网页"作为一个 const 字符串提供给 `svc_http.c`
 * 【依赖方向】无(纯数据);页面自己用 `fetch` 调 `/recordings`、`/status`、
 *             `/recordings/<名>`(Range)、`/recordings/<名>/lock`、`/recent.mp4`;
 *             样式来自 `/app.css`(见 `svc_http_page_css.h`)
 * 【线程模型】只被 `svc_http` 的 http 线程读(只读常量, 无并发问题)
 * 【资源边界】31050 字节常量(在 .rodata 里, 不占 RAM 也不占栈)
 *
 * ─────────────────────────────────────────────────────────────────
 *  ⚠️ 这个文件是**生成的** —— 不要手改, 改 `tools/assets/page.html`
 * ─────────────────────────────────────────────────────────────────
 *  生成器: `python tools/gen_page_html.py`(`--check` 校验是否过期)
 *
 * ─────────────────────────────────────────────────────────────────
 *  ⚠️ 三条硬约束(改 page.html 之前先读)
 * ─────────────────────────────────────────────────────────────────
 *  ① **不许引外部资源**:不要 CDN / 字体 / 图标库 —— 板子通常**没有外网**,
 *     引了就白屏。CSS/JS/图标全内联(图标用内联 SVG 或字符)。
 *     (参考 Frigate 用 Tailwind + React 构建、Shinobi 用 Node 打包 ——
 *      **我们要的是它们的设计语言, 不是它们的工具链**。)
 *     唯一的例外是 `/app.css`:那是**板子自己**发出去的第三方样式基底(Water.css),
 *     不是外链。
 *  ② **一行不许超过 100 显示列**(`check_spec.py` 按显示宽度算, 中文算 2 列)——
 *     这条由**生成器**保证(它在转义之后按显示宽度折行), 但 page.html 自己
 *     也别写超长行, 否则生成出来的 C 难看。
 *  ③ HTML 属性用单引号(`'`), 双引号统一由生成器转义成 `\"` —— 手写时代靠"不写双引号"
 *     避免截断 C 字符串, 现在由工具兜住(JS 里的 `"` 是合法且安全的)。
 *
 * ─────────────────────────────────────────────────────────────────
 *  UI 三层结构(2026-09-20 v3 定稿)
 * ─────────────────────────────────────────────────────────────────
 *  ① **底座** `/app.css`(Water.css v2 dark):按钮/表格/输入框/code/滚动条的地板
 *  ② **大屏层** 本文件里的 `<style>`:宽画布(1560px) + 吸顶栏 + KPI 条 +
 *     16:9 画面区 + 时间轴 + 数据表;显式夺回 Water.css 对 body 的 `max-width:800px`
 *  ③ **数据层** 内联 JS:全部手绘(canvas sparkline), 不引图表库;
 *     每秒拉一次 `/stats`, 5 秒拉一次 `/recordings`(看画面/实时时不打扰播放)
 *
 *  可访问性(照 vercel-labs/web-interface-guidelines 过了一遍):
 *    语义 `<button>`(行/时间轴块不再是"带 onclick 的 div")、图标按钮有 `aria-label`、
 *    toast 容器 `aria-live='polite'`、`:focus-visible` 焦点环、`prefers-reduced-motion`
 *    关动效、`color-scheme:dark` + `theme-color`、数字列 `tabular-nums`。
 *    一条**没采纳**的建议: 指南说"列表 >50 项要虚拟化" —— 这里一行只有 6 个节点、
 *    分页一次最多上百行, 实测没有性能问题; 反倒试过 `content-visibility:auto`,
 *    它会让**全页截图/打印里视口外的行变成空白**(`innerText` 也读不到) ——
 *    对"要截图进简历"这个用途是净损失, 所以撤掉了。
 */
#include "svc_http_page.h"

/** 回放页面(整页 HTML;见文件头三条硬约束) */
const char svc_http_page_html[] =
    "<!DOCTYPE html>\n<html lang='zh-CN'>\n<head>\n<meta charset='utf-8'>\n<meta name='viewport' co"
    "ntent='width=device-width,initial-scale=1,viewport-fit=cover'>\n<meta name='color-scheme' cont"
    "ent='dark'>\n<meta name='theme-color' content='#0a0e13'>\n<meta name='description' content='海"
    "思 IPC 板子自带的监控控制台: 实时画面 + 录像回放 + 运行数据'>\n<link rel='icon' href='data:ima"
    "ge/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%2032%2032%22%3E%"
    "3Crect%20width=%2232%22%20height=%2232%22%20rx=%228%22%20fill=%22%230a0e13%22/%3E%3Ccircle%20c"
    "x=%2216%22%20cy=%2216%22%20r=%227%22%20fill=%22none%22%20stroke=%22%234aa8ff%22%20stroke-width"
    "=%223%22/%3E%3Ccircle%20cx=%2216%22%20cy=%2216%22%20r=%222.5%22%20fill=%22%2335d07f%22/%3E%3C/"
    "svg%3E'>\n<title>IPC 监控 · 板子自带控制台</title>\n<link rel='stylesheet' href='/app.css'>\n<"
    "style>\n/* ══ 设计基线(监控大屏风) ══════════════════════════════════════════\n   底座是 Water"
    ".css(控件/排版的地板), 这一层只负责\"大屏\"该有的东西:\n   宽画布 + KPI 条 + 16:9 画面区 + 时"
    "间轴 + 数据表。\n   Water.css 会把 body 限制成 800px 居中 —— 这里必须显式夺回控制权。 */\n:roo"
    "t{\n  --bg:#0a0e13; --panel:#121821; --panel2:#171f29; --line:#243040;\n  --fg:#e9eef5; --dim:"
    "#8fa0b4; --accent:#4aa8ff; --ok:#35d07f;\n  --warn:#ffb020; --rec:#ff5c5c; --r:14px; --gap:16p"
    "x;\n  --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n}\nhtml{color-scheme:dark;"
    "scroll-behavior:smooth}\nbody{margin:0;max-width:none;padding:0;background:var(--bg);color:var"
    "(--fg);\n  font:14px/1.55 system-ui,-apple-system,'Segoe UI',Roboto,'Noto Sans SC',sans-serif;"
    "\n  -webkit-font-smoothing:antialiased;touch-action:manipulation;\n  -webkit-tap-highlight-col"
    "or:transparent}\n*,*::before,*::after{box-sizing:border-box}\nh1,h2,h3{margin:0;font-weight:65"
    "0;color:var(--fg);text-wrap:balance}\nh1{font-size:16px;letter-spacing:.2px}\nh2{font-size:13p"
    "x;color:var(--dim);font-weight:600}\np{margin:0}\nimg,video{max-width:100%}\n[hidden]{display:"
    "none!important}\ncode{font-family:var(--mono);font-size:12px}\n.num{font-variant-numeric:tabul"
    "ar-nums}\n.skip{position:absolute;left:-9999px;top:0;z-index:99;background:var(--accent);\n  c"
    "olor:#04121f;padding:8px 12px;border-radius:0 0 8px 0;font-weight:600}\n.skip:focus{left:0}\n:"
    "focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:8px}\n/* ── 顶"
    "栏(吸顶) ── */\n.top{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:12px"
    ";\n  padding:calc(8px + env(safe-area-inset-top)) 20px 8px;\n  background:rgba(10,14,19,.86);b"
    "ackdrop-filter:blur(10px);\n  border-bottom:1px solid var(--line);min-height:56px;flex-wrap:wr"
    "ap}\n.brand{display:flex;align-items:center;gap:10px;min-width:0}\n.logo{width:26px;height:26p"
    "x;border-radius:8px;flex:0 0 auto;\n  background:linear-gradient(140deg,#4aa8ff,#2ecc71);displ"
    "ay:grid;place-items:center;\n  color:#06121e;font-size:14px;font-weight:800}\n.brand h1 span{d"
    "isplay:block;color:var(--dim);font-weight:400;font-size:12px}\n.pills{display:flex;gap:8px;fle"
    "x-wrap:wrap;min-width:0}\n.pill{display:inline-flex;align-items:center;gap:7px;padding:5px 11p"
    "x;font-size:12px;\n  color:var(--dim);background:var(--panel2);border:1px solid var(--line);\n"
    "  border-radius:999px;white-space:nowrap;max-width:min(60vw,520px);overflow:hidden;\n  text-ov"
    "erflow:ellipsis}\n.pill b,.pill .v{color:var(--fg);font-weight:600}\n.dot{width:7px;height:7px"
    ";border-radius:50%;background:var(--dim);flex:0 0 auto}\n.dot.on{background:var(--rec);animati"
    "on:pulse 1.6s ease-in-out infinite}\n.dot.live{background:var(--ok);animation:pulse 1.6s ease-"
    "in-out infinite}\n@keyframes pulse{50%{opacity:.35}}\n.spacer{flex:1 1 auto}\n/* ── 画布 ── */"
    "\nmain{max-width:1560px;margin:0 auto;padding:var(--gap) 20px 48px;\n  padding-bottom:calc(48p"
    "x + env(safe-area-inset-bottom))}\n/* ── KPI 条 ── */\n.kpis{display:grid;gap:10px;margin-bott"
    "om:var(--gap);\n  grid-template-columns:repeat(auto-fit,minmax(140px,1fr))}\n.kpi{background:v"
    "ar(--panel);border:1px solid var(--line);border-radius:12px;\n  padding:10px 12px;min-width:0}"
    "\n.kpi .k{color:var(--dim);font-size:12px;display:flex;align-items:center;gap:6px;\n  white-sp"
    "ace:nowrap;overflow:hidden;text-overflow:ellipsis}\n.kpi .v{font-size:21px;font-weight:680;lin"
    "e-height:1.25;\n  font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden;\n  tex"
    "t-overflow:ellipsis}\n.kpi .u{color:var(--dim);font-size:12px;margin-left:4px;font-weight:400}"
    "\n.kpi .sub{color:var(--dim);font-size:11px;font-variant-numeric:tabular-nums}\n.spark{width:1"
    "00%;height:34px;display:block;margin-top:6px}\n/* ── 主栅格 ── */\n.grid{display:grid;gap:var("
    "--gap);align-items:start;\n  grid-template-columns:minmax(0,2.05fr) minmax(320px,1fr)}\n@media"
    " (max-width:1040px){.grid{grid-template-columns:1fr}}\n.card{background:var(--panel);border:1p"
    "x solid var(--line);border-radius:var(--r);\n  overflow:hidden}\n.card+.card{margin-top:var(--"
    "gap)}\n.cardhd{display:flex;align-items:center;gap:10px;padding:12px 14px;\n  border-bottom:1p"
    "x solid var(--line);background:var(--panel2);flex-wrap:wrap}\n.cardhd h2{font-size:13px}\n.car"
    "dhd .k{color:var(--dim);font-size:12px}\n.cardbd{padding:14px}\n/* ── 画面区 ── */\n.stage{pos"
    "ition:relative;background:#000;aspect-ratio:16/9}\n.stage video,.stage img{position:absolute;i"
    "nset:0;width:100%;height:100%;\n  object-fit:contain;background:#000}\n.badge{position:absolut"
    "e;left:12px;top:12px;z-index:3;display:flex;gap:6px;\n  align-items:center;padding:5px 10px;bo"
    "rder-radius:999px;font-size:12px;\n  background:rgba(6,10,15,.72);border:1px solid #2b3743;\n "
    " backdrop-filter:blur(4px);font-variant-numeric:tabular-nums}\n.overlay{position:absolute;righ"
    "t:12px;top:12px;z-index:3;display:flex;gap:6px}\n.stage .empty{position:absolute;inset:0;displ"
    "ay:grid;place-content:center;gap:6px;\n  text-align:center;color:var(--dim);font-size:13px;pad"
    "ding:20px}\n.stage .empty b{color:var(--fg);font-size:15px}\n.bar{display:flex;gap:8px;align-i"
    "tems:center;flex-wrap:wrap;padding:12px 14px;\n  border-top:1px solid var(--line)}\n/* ── 按钮"
    "(Water.css 打底, 这里只调密度与状态) ── */\nbutton{cursor:pointer;font-variant-numeric:tabular"
    "-nums}\nbutton.icon{padding:7px 10px;line-height:1;font-size:14px}\nbutton.primary{font-weight"
    ":650}\nbutton.ghost{background:transparent}\nbutton.on{box-shadow:inset 0 0 0 1px var(--accent"
    ")}\n.acts{display:flex;gap:6px;flex:0 0 auto}\n.acts button{padding:5px 9px;font-size:12px;bor"
    "der-radius:8px}\nlabel.chk{display:inline-flex;align-items:center;gap:7px;color:var(--dim);\n "
    " font-size:12px;cursor:pointer;user-select:none}\ninput[type=checkbox]{accent-color:var(--acce"
    "nt);width:15px;height:15px;margin:0}\n/* ── 时间轴 ── */\n.timeline{position:relative;height:5"
    "4px;margin:0 14px 14px;border-radius:10px;\n  background:#0c1219;border:1px solid var(--line);"
    "overflow:hidden}\n.tl-hint{position:absolute;left:10px;bottom:5px;font-size:11px;color:var(--d"
    "im);\n  pointer-events:none}\n.tl-now{position:absolute;top:0;bottom:0;right:0;width:2px;backg"
    "round:var(--rec)}\n.blk{position:absolute;top:7px;bottom:19px;padding:0;border-radius:5px;curs"
    "or:pointer;\n  background:#26374b;border:1px solid #34506c;transition:transform .1s,border-col"
    "or .1s}\n.blk:hover{transform:translateY(-1px);border-color:#5b86ad}\n.blk.lock{background:#4a"
    "3410;border-color:#7a5a1c}\n.blk.rec{background:#3a1416;border-color:#7a2a2f}\n.blk.cur{outlin"
    "e:2px solid var(--accent);outline-offset:1px}\n/* ── 录像列表 ── */\n.rows{max-height:min(58vh"
    ",520px);overflow:auto;overscroll-behavior:contain}\n@media (max-width:1040px){.rows{max-height"
    ":320px}}\n.row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;\n  align-items:c"
    "enter;padding:9px 14px;border-top:1px solid var(--line)}\n.row:hover{background:#161e28}\n.row"
    ".sel{background:#152a3d;box-shadow:inset 3px 0 0 var(--accent)}\n.rowmain{display:block;width:"
    "100%;min-width:0;text-align:left;background:none;\n  border:0;padding:0;color:var(--fg);font:i"
    "nherit;cursor:pointer}\n.rowmain:hover{background:none}\n.rowmain:disabled{color:var(--fg);opa"
    "city:1;cursor:default}\n.row .t{font-weight:650;color:var(--fg);font-variant-numeric:tabular-n"
    "ums}\n.row .m{color:var(--dim);font-size:12px;display:flex;gap:8px;align-items:center;\n  flex"
    "-wrap:wrap;min-width:0}\n.tag{padding:1px 7px;border-radius:999px;font-size:11px;border:1px so"
    "lid}\n.tag.lock{color:var(--warn);border-color:#6b4d12;background:#2c2208}\n.tag.live{color:va"
    "r(--rec);border-color:#6b2226;background:#2c0f11}\n.skel{height:44px;border-top:1px solid var("
    "--line);opacity:.5}\n/* ── 数据表 ── */\n.tbl{width:100%;border-collapse:collapse;font-size:12"
    ".5px}\n.tbl caption{text-align:left;color:var(--dim);font-size:12px;padding:0 0 6px}\n.tbl th,"
    ".tbl td{padding:7px 8px;border-top:1px solid var(--line);text-align:left}\n.tbl th{color:var(-"
    "-dim);font-weight:550;white-space:nowrap}\n.tbl td.n{font-variant-numeric:tabular-nums;text-al"
    "ign:right;white-space:nowrap}\n.tbl td:first-child,.tbl th:first-child{padding-left:0}\n.tbl t"
    "d:last-child,.tbl th:last-child{padding-right:0}\n/* ── 存储条 / 提示 ── */\n.stbar{height:12p"
    "x;border-radius:6px;background:#0c1219;overflow:hidden;\n  border:1px solid var(--line);margin"
    "-top:8px}\n.stbar i{display:block;height:100%;background:linear-gradient(90deg,#4aa8ff,#35d07f"
    ")}\n.note{color:var(--dim);font-size:12.5px;line-height:1.9}\n.note b{color:var(--fg)}\n.note "
    ".kv{display:grid;gap:2px 10px;grid-template-columns:auto minmax(0,1fr);\n  margin-bottom:10px}"
    "\n.note kbd{font:12px var(--mono);background:var(--panel2);border:1px solid var(--line);\n  bo"
    "rder-bottom-width:2px;border-radius:6px;padding:1px 6px;color:var(--fg)}\n/* ── toast ── */\n#"
    "toasts{position:fixed;right:16px;bottom:16px;z-index:60;display:flex;\n  flex-direction:column"
    ";gap:8px;max-width:min(92vw,340px)}\n.toast{background:#182029;border:1px solid var(--line);bo"
    "rder-left:3px solid var(--ok);\n  border-radius:10px;padding:10px 12px;font-size:13px;box-shad"
    "ow:0 10px 30px #0009;\n  animation:in .18s ease-out}\n.toast.err{border-left-color:var(--rec)}"
    "\n@keyframes in{from{opacity:0;transform:translateY(6px)}}\n.spin{display:inline-block;width:1"
    "2px;height:12px;border-radius:50%;\n  border:2px solid #ffffff55;border-top-color:#fff;animati"
    "on:sp .7s linear infinite}\n@keyframes sp{to{transform:rotate(360deg)}}\n/* 窄屏: 时间轴的说明"
    "文字会跟色块抢地方, 直接收起来; 键值对改成上下排 */\n@media (max-width:560px){\n  .tl-hint{dis"
    "play:none}\n  .timeline{height:62px}\n  .blk{bottom:7px}\n  .note .kv{grid-template-columns:1f"
    "r;gap:0 0}\n  .note .kv span:nth-child(odd){color:var(--fg);margin-top:6px}\n  .tbl th,.tbl td"
    "{padding:6px 5px}\n  .blk{min-width:6px}\n}\n/* 尊重系统设置: 关掉动效(前庭功能敏感的用户) */"
    "\n@media (prefers-reduced-motion:reduce){\n  *,*::before,*::after{animation:none!important;tra"
    "nsition:none!important;\n    scroll-behavior:auto!important}\n}\n</style>\n</head>\n<body>\n<a"
    " class='skip' href='#main'>跳到主内容</a>\n<header class='top'>\n  <div class='brand'>\n    <s"
    "pan class='logo' aria-hidden='true'>◉</span>\n    <h1>IPC 监控<span>板子自带控制台 · 零安装 · "
    "离线可用</span></h1>\n  </div>\n  <div class='pills'>\n    <span class='pill'><i class='dot' i"
    "d='recdot' aria-hidden='true'></i>\n      <span id='stat' class='num'>连接中…</span></span>\n "
    "   <span class='pill' id='livepill' hidden><i class='dot live' aria-hidden='true'></i>\n      "
    "实时画面 <span id='livemeta' class='v num'></span></span>\n    <span class='pill'><span class="
    "'k'>板端</span> <b id='devurl' class='num'>-</b></span>\n  </div>\n  <span class='spacer'></sp"
    "an>\n  <button id='brefresh' class='icon' aria-label='刷新状态与录像列表' title='刷新 (R)'>⟳</"
    "button>\n</header>\n<main id='main'>\n  <section class='kpis' id='kpis' aria-label='运行数据总"
    "览'></section>\n  <div class='grid'>\n    <section class='card' aria-label='画面与时间轴'>\n  "
    "    <div class='stage' id='stage'>\n        <div class='badge' id='badge'>未播放</div>\n      "
    "  <div class='overlay'>\n          <button id='bfs' class='icon' aria-label='全屏' title='全屏"
    " (F)'>⛶</button>\n          <button id='bsnap' class='icon' aria-label='抓图保存' title='抓图 "
    "(S)'>⤓</button>\n        </div>\n        <div class='empty' id='emptymsg'>\n          <b>还没"
    "有画面</b>\n          <span>右边列表点一段回放, 或点下面的『● 看实时』</span>\n        </div>"
    "\n        <img id='live' alt='实时画面(MJPEG 连续帧)' hidden>\n        <video id='v' controls "
    "playsinline preload='none' hidden></video>\n      </div>\n      <div class='bar'>\n        <bu"
    "tton id='bliveoff' class='primary' aria-pressed='false'>● 看实时</button>\n        <button id="
    "'brec'>看最新(收尾当前段)</button>\n        <button id='bprev' class='icon' aria-label='上一段"
    "' title='上一段 (←)'>◀</button>\n        <button id='bnext' class='icon' aria-label='下一段' t"
    "itle='下一段 (→)'>▶</button>\n        <span class='spacer'></span>\n        <span class='pill'"
    " id='cur'>没有选中</span>\n      </div>\n      <div class='timeline' id='bar' role='group' ari"
    "a-label='录像时间轴(每块一段)'>\n        <div class='tl-hint'>时间轴: 每块一段(宽度∝文件大小) "
    "· 橙=已锁定 · 红=正在录</div>\n        <div class='tl-now' id='tlnow' hidden></div>\n      </d"
    "iv>\n    </section>\n    <aside class='card' aria-label='录像列表'>\n      <div class='cardhd'"
    ">\n        <h2 id='listcnt'>录像</h2>\n        <span class='spacer'></span>\n        <label cl"
    "ass='chk'><input type='checkbox' id='auto' checked>自动刷新</label>\n      </div>\n      <div "
    "id='rec'></div>\n      <div class='rows' id='tb' role='list' aria-label='录像分段列表'></div>"
    "\n      <div class='bar'>\n        <button id='bmore'>加载更早</button>\n        <span class='"
    "spacer'></span>\n        <button id='bcopy' class='ghost'>复制播放列表链接</button>\n      </d"
    "iv>\n    </aside>\n  </div>\n  <section class='card' aria-label='趋势与存储'>\n    <div class="
    "'cardhd'>\n      <h2>运行趋势 · 存储</h2>\n      <span class='spacer'></span>\n      <span cla"
    "ss='k'>采样起点 <b id='uptime' class='num'>-</b></span>\n    </div>\n    <div class='cardbd'>"
    "\n      <div class='kpis' id='sparks'></div>\n      <p class='note'>存储(录制分区): <b id='dis"
    "kmsg' class='num'>-</b></p>\n      <div class='stbar' role='img' aria-label='录制分区已用比例'"
    ">\n        <i id='diskbar' style='width:0'></i></div>\n    </div>\n  </section>\n  <section cl"
    "ass='card' aria-label='通道现状'>\n    <div class='cardhd'><h2>通道现状</h2></div>\n    <div c"
    "lass='cardbd'>\n      <table class='tbl' id='clients'>\n        <caption>四路各自独立: RTSP 直"
    "播 / MJPEG 实时 / 回放 HTTP / 录制</caption>\n      </table>\n    </div>\n  </section>\n  <sec"
    "tion class='card' aria-label='用法与快捷键'>\n    <div class='cardbd note'>\n      <div class="
    "'kv'>\n        <span>实时画面</span><span><code id='liveurl'>-</code>(MJPEG, 板子侧按需开硬件 "
    "JPEG 通道)</span>\n        <span>整段连播</span><span><code id='m3u'>-</code>(VLC / mpv 直接打"
    "开)</span>\n        <span>直播拉流</span><span><code id='rtsp'>-</code>(RTSP, 浏览器播不了)</s"
    "pan>\n      </div>\n      快捷键: <kbd>空格</kbd> 播放/暂停 · <kbd>←</kbd><kbd>→</kbd> 上一段/"
    "下一段 ·\n      <kbd>L</kbd> 实时 · <kbd>R</kbd> 刷新 · <kbd>F</kbd> 全屏 · <kbd>S</kbd> 抓图"
    "\n    </div>\n  </section>\n</main>\n<div id='toasts' aria-live='polite' aria-atomic='false'><"
    "/div>\n<script>\nvar segs=[],total=0,pages=1,reclen=0,liveUrl='',sel=-1,timer=0,busy=false;\nv"
    "ar mode='none',lastTap=0;\nfunction $(id){return document.getElementById(id);}\nfunction fmt(n"
    "){n=n||0;\n  if(n>=1073741824)return (n/1073741824).toFixed(2)+' GB';\n  if(n>=1048576)return "
    "(n/1048576).toFixed(1)+' MB';\n  if(n>=1024)return (n/1024).toFixed(0)+' KB';\n  return n+' B'"
    ";}\n/* 段名形如 `2026-09-21-21-01-46.mp4` —— 列表/横幅/toast 一律显示**完整日期+时间**,\n   形"
    "如 `2026-09-21 21:01:46`(冒号, 与主流 NVR/IPC 界面一致)。\n   原实现只取 `substr(11,8)`(即 `HH"
    "-MM-SS`), 于是\"不知道是哪一天的\"\n   (用户 2026-09-21 反馈)。⚠️ 长度不足 19 的异常名原样返回"
    ", 不截不猜。 */\nfunction dt(s){s=s||'';return s.length>=19?\n  s.substr(0,10)+' '+s.substr(11"
    ",8).replace(/-/g,':'):s;}\nfunction hm(sec){var m=Math.floor((sec||0)/60);\n  return m>=60?Mat"
    "h.floor(m/60)+' 小时 '+(m%60)+' 分':m+' 分钟';}\nfunction toast(msg,bad){var d=document.create"
    "Element('div');\n  d.className='toast'+(bad?' err':'');d.textContent=msg;\n  $('toasts').appen"
    "dChild(d);\n  setTimeout(function(){d.style.opacity='0';\n    setTimeout(function(){d.remove()"
    ";},200);},bad?6000:3200);}\nfunction fail(e){toast('出错: '+(e&&e.message?e.message:e),1);}\na"
    "sync function api(p){var r=await fetch(p,{cache:'no-store'});\n  if(!r.ok)throw new Error('HTT"
    "P '+r.status+' '+p);return r.json();}\nfunction setBusy(b){busy=b;$('brec').disabled=b;$('bmor"
    "e').disabled=b;\n  $('bliveoff').disabled=b;}\n/* ── 数据面板(全部手绘: 不引图表库, 板子没外网"
    ") ── */\nvar S=null;\nfunction d1(x){return (x/10).toFixed(1);}\nfunction kpi(k,v,u,sub){retur"
    "n '<div class=kpi><div class=k><span>'+k+\n  '</span></div><div class=\"v num\">'+v+(u?'<span "
    "class=u>'+u+'</span>':'')+\n  '</div>'+(sub?'<div class=\"sub num\">'+sub+'</div>':'')+'</div>"
    "';}\nfunction spark(vals,color){\n  var w=240,h=34,c=document.createElement('canvas');\n  c.cl"
    "assName='spark';c.width=w;c.height=h;\n  var g=c.getContext('2d'),mx=1,i,q,x,y;\n  for(i=0;i<v"
    "als.length;i++)if(vals[i]>mx)mx=vals[i];\n  g.strokeStyle=color;g.lineWidth=2;g.lineJoin='roun"
    "d';g.beginPath();\n  for(i=0;i<vals.length;i++){\n    q=vals[i]/mx;x=vals.length<2?0:i*(w-2)/("
    "vals.length-1);y=h-2-q*(h-8);\n    if(i===0)g.moveTo(x,y);else g.lineTo(x,y);\n  }\n  g.stroke"
    "();\n  g.globalAlpha=.22;g.lineTo(w-2,h);g.lineTo(0,h);g.closePath();\n  g.fillStyle=color;g.f"
    "ill();\n  return c;\n}\nfunction drawStats(){\n  if(!S)return;\n  var h=S.hist||[],m=[],r=[],l"
    "=[],i;\n  for(i=0;i<h.length;i++){m.push(h[i][1]);r.push(h[i][2]);l.push(h[i][3]);}\n  var las"
    "t=h.length?h[h.length-1]:[0,0,0,0,0,0];\n  var onrec=(S.rec&&S.rec.recording)?1:0;\n  if(!onre"
    "c)last[5]=0;\n  var rec=S.rec||{},segs_=S.segs||{},http=S.http||{},rtsp=S.rtsp||{};\n  var age"
    "=(rtsp.clients?rtsp.age_ms:'—');\n  $('kpis').innerHTML=\n    kpi('取流帧率',d1(last[1]),'fps'"
    ",'主编码通道')+\n    kpi('录制码流',last[2],'KB/s',(rec.recording?'正在录':'未在录'))+\n    kp"
    "i('实时帧率',d1(last[3]),'fps','MJPEG')+\n    kpi('实时观看',(last[4]||0),'人','上限 4')+\n   "
    " kpi('RTSP 客户端',(rtsp.clients||0),'个','上限 8')+\n    kpi('发送丢帧',last[5],'帧/秒','队列"
    "满时丢')+\n    kpi('帧龄(发送侧)',age,(rtsp.clients?'ms':''),\n      (rtsp.clients?'越小越好':"
    "'没有客户端, 没得测'))+\n    kpi('录像分段',(segs_.files||0),'个','锁定 '+(segs_.locked||0))+"
    "\n    kpi('回放请求',(http.files||0),'次','206 段 '+(http.partials||0))+\n    kpi('已发送',fmt"
    "(http.bytes_sent),'','本次开机累计');\n  $('sparks').innerHTML='';\n  if(m.length>1){\n    [['"
    "取流 fps',m,'#4aa8ff'],['录制 KB/s',r,'#35d07f'],\n     ['实时 fps',l,'#ffb020']].forEach(func"
    "tion(t){\n      var d=document.createElement('div');d.className='kpi';\n      d.appendChild(sp"
    "ark(t[1],t[2]));\n      var s=document.createElement('div');s.className='k';\n      s.textCont"
    "ent=t[0]+' · 最近 '+t[1].length+' 秒';d.appendChild(s);\n      $('sparks').appendChild(d);});"
    "\n  }else{$('sparks').innerHTML=kpi('趋势图','采样中…','','每秒一个点');}\n  var tot=(S.disk.t"
    "otal||0),free=(S.disk.free||0),used=Math.max(0,tot-free);\n  var pct=tot?Math.max(0,Math.min(1"
    "00,used/tot*100)):0;\n  $('diskbar').style.width=pct.toFixed(1)+'%';\n  var rate=(last[2]||0)*"
    "1024;\n  var hrs=rate>1024?free/rate/3600:0;\n  $('diskmsg').textContent=fmt(used)+' / '+fmt(t"
    "ot)+' · 已用 '+pct.toFixed(0)+\n    '% · 剩 '+fmt(free)+(hrs>0?' · 按当前码率还能录 ~'+hrs.toF"
    "ixed(1)+' 小时':'');\n  $('uptime').textContent=(S.hist_t0?new Date(S.hist_t0*1000)\n    .toLo"
    "caleTimeString():'-');\n  var lv=(S.live&&S.live.target_fps)?S.live.target_fps:'?';\n  var lq="
    "(S.live&&S.live.q)?S.live.q:'?';\n  var t='<tr><th>通道</th><th>现状</th><th class=n>计数</th>"
    "</tr>';\n  t+='<tr><td>RTSP 直播</td><td>'+(rtsp.clients||0)+' 个客户端'+\n    (rtsp.wait_idr?"
    "' · '+rtsp.wait_idr+' 个在等 IDR':'')+'</td><td class=n>'+\n    (rtsp.sent_kb||0)+' KB</td></t"
    "r>';\n  t+='<tr><td>MJPEG 实时</td><td>'+d1(last[3])+' fps · 观看 '+(last[4]||0)+\n    ' 人 · "
    "档位 '+lv+'fps/q'+lq+'</td><td class=n>'+(last[4]||0)+' 人</td></tr>';\n  t+='<tr><td>回放 HTT"
    "P</td><td>串行: 一次只服务一个请求</td><td class=n>'+\n    (http.files||0)+' 次 / '+fmt(http.b"
    "ytes_sent)+'</td></tr>';\n  t+='<tr><td>录制</td><td>'+(rec.recording?'正在录 '+dt(rec.name)+"
    "\n    ' · 本段 '+fmt(rec.cur_bytes):'未在录')+'</td><td class=n>'+\n    (rec.segments||0)+' 段"
    " / 删 '+(rec.deleted||0)+' / 错 '+\n    (rec.write_errors||0)+'</td></tr>';\n  $('clients').in"
    "nerHTML=t;\n}\nasync function loadStats(){try{S=await api('/stats');drawStats();}catch(e){}}\n"
    "/* ── 画面区 ── */\nfunction badge(t){$('badge').textContent=t;}\nfunction showOnly(which){mod"
    "e=which;\n  $('v').hidden=(which!=='video');\n  $('live').hidden=(which!=='live');\n  $('empty"
    "msg').hidden=(which!=='none');}\nfunction setLiveBtn(on){var b=$('bliveoff');\n  b.className=o"
    "n?'on':'primary';b.setAttribute('aria-pressed',on?'true':'false');\n  b.textContent=on?'■ 关掉"
    "实时':'● 看实时';}\n/* ── 列表与时间轴 ── */\nfunction addRow(i,rec){\n  var s=rec?null:segs[i"
    "],row=document.createElement('div');\n  /* ⚠️ 正在录的那一行用 i===-1 传进来, 而 sel 初值也是 "
    "-1 —— 不排除它的话\n     这一行会被当成\"选中\"(实际发生过: 量出来底色是 .sel 的 #152a3d)。 */"
    "\n  row.className='row'+(rec?'':(i===sel?' sel':''));\n  row.setAttribute('role','listitem');"
    "\n  var main=document.createElement('button');main.type='button';main.className='rowmain';\n  "
    "main.setAttribute('data-name',rec?rec.name:s.name);   /* 全名也给出来: 深链/自动化要它 */\n  v"
    "ar t=document.createElement('div');t.className='t num';\n  t.textContent=rec?dt(rec.name):dt(s"
    ".name);\n  var m=document.createElement('div');m.className='m';\n  m.appendChild(document.crea"
    "teTextNode(fmt(rec?rec.bytes:s.size)));\n  if(s&&s.locked){var g=document.createElement('span'"
    ");g.className='tag lock';\n    g.textContent='已锁定';m.appendChild(g);}\n  if(rec){var g2=doc"
    "ument.createElement('span');g2.className='tag live';\n    g2.textContent='正在录';m.appendChil"
    "d(g2);}\n  main.appendChild(t);main.appendChild(m);\n  if(rec){main.disabled=true;\n    main.s"
    "etAttribute('aria-label','正在录制的一段: '+t.textContent);}\n  else{main.onclick=function(){p"
    "lay(i);};}\n  row.appendChild(main);\n  if(!rec){\n    var acts=document.createElement('div');"
    "acts.className='acts';\n    var bl=document.createElement('button');bl.type='button';\n    bl."
    "textContent=s.locked?'解锁':'锁定';\n    bl.setAttribute('aria-label',(s.locked?'解锁':'锁定')"
    "+' '+t.textContent);\n    bl.onclick=function(ev){ev.stopPropagation();lock(i);};\n    var bs="
    "document.createElement('button');bs.type='button';bs.textContent='另存';\n    bs.setAttribute("
    "'aria-label','另存 '+t.textContent);\n    bs.onclick=function(ev){ev.stopPropagation();save(i)"
    ";};\n    acts.appendChild(bl);acts.appendChild(bs);row.appendChild(acts);\n  }\n  $('tb').appe"
    "ndChild(row);\n}\nfunction render(){\n  var tb=$('tb');tb.textContent='';var bar=$('bar');\n  "
    "var old=bar.querySelectorAll('.blk'),q;\n  for(q=0;q<old.length;q++)old[q].remove();\n  $('lis"
    "tcnt').textContent='录像 '+(total||segs.length)+' 段';\n  $('tlnow').hidden=!reclen;\n  if(rec"
    "len)addRow(-1,reclen);\n  var sumsz=0,k;for(k=0;k<segs.length;k++)sumsz+=segs[k].size;\n  if(s"
    "umsz<=0)sumsz=1;\n  for(k=0;k<segs.length;k++){\n    addRow(k,null);\n    var b=document.creat"
    "eElement('button');b.type='button';\n    b.className='blk'+(segs[k].locked?' lock':'')+(k===se"
    "l?' cur':'');\n    b.title=dt(segs[k].name)+' · '+fmt(segs[k].size)+\n      (segs[k].locked?' "
    "· 已锁定':'');\n    b.setAttribute('aria-label','播放 '+dt(segs[k].name));\n    b.style.width="
    "Math.max(0.6,segs[k].size/sumsz*100)+'%';\n    b.onclick=function(x){return function(){play(x)"
    ";};}(k);\n    bar.appendChild(b);\n  }\n  if(sel>=0){var cur=tb.querySelector('.row.sel');\n  "
    "  if(cur&&cur.scrollIntoView)cur.scrollIntoView({block:'nearest'});}\n}\nasync function loadLi"
    "st(){try{\n  var d=await api('/recordings');segs=d.segments||[];\n  total=d.count||segs.length"
    ";pages=1;render();openHash();\n }catch(e){fail(e);}}\nasync function more(){try{\n  if(!segs.l"
    "ength){toast('还没有可加载的',1);return;}\n  setBusy(true);\n  var last=segs[segs.length-1].na"
    "me;\n  var d=await api('/recordings?before='+encodeURIComponent(last));\n  if(!d.segments||!d."
    "segments.length){toast('没有更早的了');}\n  else{segs=segs.concat(d.segments);pages++;total=d."
    "count||total;render();\n    toast('又加载了 '+d.segments.length+' 段');}\n }catch(e){fail(e);}"
    "setBusy(false);}\nasync function loadStatus(){try{\n  var d=await api('/status');\n  if(d.reco"
    "rding){reclen=d;\n    var grew=Math.max(0,Math.floor((Date.now()/1000)-d.started_at));\n    $("
    "'recdot').className='dot on';\n    $('stat').textContent='正在录 '+dt(d.name)+' · 已 '+hm(grew"
    ")+\n      ' · '+fmt(d.bytes);\n  }else{reclen=0;$('recdot').className='dot';\n    $('stat').te"
    "xtContent='没有在录';}\n  if(d.live_mjpg){liveUrl=d.live_mjpg;$('liveurl').textContent=liveUrl"
    ";}\n  else{liveUrl='';$('liveurl').textContent='(未启用: 板子用 -no-live 起的)';}\n  $('rtsp')"
    ".textContent=d.live_rtsp||('rtsp://'+location.hostname+':8554/live');\n  $('m3u').textContent="
    "location.origin+'/playlist.m3u';\n }catch(e){$('recdot').className='dot';\n  $('stat').textCon"
    "tent='连不上服务';fail(e);}}\n/* ── 播放 / 实时 ── */\nfunction wantLive(){return /(^|[#&])liv"
    "e\\b/.test(location.hash);}\nfunction wantSeg(){var m=/#s=([^&]+)/.exec(location.hash);\n  ret"
    "urn m?decodeURIComponent(m[1]):'';}\nfunction openHash(){\n  if(wantLive()){liveOnClick();retu"
    "rn;}\n  var n=wantSeg(),k;\n  for(k=0;k<segs.length;k++)if(segs[k].name===n){play(k);return;}"
    "\n}\nfunction play(i){var s=segs[i];if(!s)return;sel=i;liveOff();\n  showOnly('video');$('v')."
    "src=s.uri;badge('回放 '+dt(s.name));\n  $('cur').textContent=dt(s.name);\n  if(location.hash.i"
    "ndexOf('#s='+encodeURIComponent(s.name))<0)\n    location.hash='s='+encodeURIComponent(s.name)"
    ";\n  render();\n  $('v').play().catch(function(){});}\nfunction step(d){if(!segs.length)return"
    ";\n  var n=sel<0?0:sel+d;if(n<0)n=0;if(n>=segs.length)n=segs.length-1;play(n);}\nfunction live"
    "On(){return mode==='live';}\nfunction liveOff(){if(mode==='live'){$('live').removeAttribute('s"
    "rc');}\n  $('live').hidden=true;\n  $('livepill').hidden=true;setLiveBtn(false);\n  if(mode==="
    "'live'){mode='none';showOnly(sel>=0?'video':'none');\n    if(sel>=0){$('v').src=segs[sel].uri;"
    "$('v').play().catch(function(){});}\n    badge(sel>=0?'回放 '+dt(segs[sel].name):'未播放');}}"
    "\nfunction liveOnClick(){if(liveOn()){liveOff();$('cur').textContent='实时已关';\n    return;}"
    "\n  if(!liveUrl){toast('这台设备的实时画面没开(-no-live 起的)',1);return;}\n  $('v').pause();s"
    "howOnly('live');\n  $('live').src=liveUrl+'?t='+Date.now();badge('● 实时(MJPEG)');\n  $('livep"
    "ill').hidden=false;$('livemeta').textContent='正在看';\n  setLiveBtn(true);$('cur').textConten"
    "t='实时画面';\n  toast('实时画面已开(板子侧按需开了编码通道)');}\nasync function recent(){try{"
    "\n  setBusy(true);$('brec').innerHTML='<i class=spin></i> 收尾中…';\n  var r=await fetch('/rec"
    "ent.mp4',{method:'HEAD',cache:'no-store'});\n  if(!r.ok)throw new Error('HTTP '+r.status+' /re"
    "cent.mp4');\n  var n=r.headers.get('X-Recent-Clip');\n  if(!n)throw new Error('应答里没有 X-Re"
    "cent-Clip');\n  await loadList();\n  var k=0,q;for(q=0;q<segs.length;q++)if(segs[q].name===n)k"
    "=q;\n  play(k);toast('已收尾并开始播放: '+dt(n));\n }catch(e){fail(e);}setBusy(false);\n $('br"
    "ec').textContent='看最新(收尾当前段)';}\nasync function lock(i){var s=segs[i];if(!s)return;\n "
    " var want=s.locked?0:1;s.locked=want;render();\n  try{var r=await fetch(s.lock_uri,{method:'PU"
    "T',body:String(want)});\n    if(!r.ok)throw new Error('HTTP '+r.status);\n    toast(want?'已锁"
    "定: '+dt(s.name):'已解锁: '+dt(s.name));\n  }catch(e){s.locked=want?0:1;render();fail(e);}}\nf"
    "unction save(i){var s=segs[i];if(!s)return;var a=document.createElement('a');\n  a.href=s.uri;"
    "a.download=s.name;document.body.appendChild(a);a.click();\n  a.remove();toast('开始下载 '+dt(s"
    ".name));}\nfunction snap(){if(!liveOn()){if(sel>=0)save(sel);\n    else toast('先播放点什么, "
    "或打开实时画面',1);return;}\n  try{var im=$('live');var c=document.createElement('canvas');\n "
    "   c.width=im.naturalWidth||640;c.height=im.naturalHeight||360;\n    c.getContext('2d').drawIm"
    "age(im,0,0);\n    var a=document.createElement('a');\n    a.href=c.toDataURL('image/png');a.do"
    "wnload='live_'+Date.now()+'.png';\n    document.body.appendChild(a);a.click();a.remove();\n   "
    " toast('已抓图(当前实时帧)');\n  }catch(e){fail(e);}}\nfunction full(){var s=$('stage');\n  if"
    "(document.fullscreenElement){document.exitFullscreen();}\n  else if(s.requestFullscreen){s.req"
    "uestFullscreen();}}\nasync function copyLink(){var u=location.origin+'/playlist.m3u';\n  try{a"
    "wait navigator.clipboard.writeText(u);toast('已复制: '+u);}\n  catch(e){toast('复制失败, 手动"
    "访问 '+u,1);}}\nasync function tick(){await loadStatus();if(busy)return;\n  var v=$('v');\n  i"
    "f(liveOn()||!v.paused)render();else await loadList();}\nfunction startAuto(){if(timer)clearInt"
    "erval(timer);\n  if($('auto').checked)timer=setInterval(tick,5000);}\n$('brefresh').onclick=fu"
    "nction(){tick();toast('已刷新');};\n$('brec').onclick=function(){recent();};\n$('bliveoff').on"
    "click=function(){liveOnClick();};\n$('bmore').onclick=function(){more();};\n$('bprev').onclick"
    "=function(){step(-1);};\n$('bnext').onclick=function(){step(1);};\n$('bsnap').onclick=function"
    "(){snap();};\n$('bfs').onclick=function(){full();};\n$('bcopy').onclick=function(){copyLink();"
    "};\n$('auto').onchange=function(){localStorage.setItem('ipcAuto',\n  $('auto').checked?'1':'0'"
    ");startAuto();};\nwindow.addEventListener('hashchange',function(){openHash();});\ndocument.add"
    "EventListener('keydown',function(e){\n  if(e.target.closest&&e.target.closest('input,textarea,"
    "select,button,a'))return;\n  var k=e.key;\n  if(e.code==='Space'){e.preventDefault();\n    if("
    "!liveOn()){if($('v').paused)$('v').play();else $('v').pause();}}\n  else if(k==='ArrowLeft')st"
    "ep(-1);\n  else if(k==='ArrowRight')step(1);\n  else if(k==='l'||k==='L')liveOnClick();\n  els"
    "e if(k==='r'||k==='R'){tick();toast('已刷新');}\n  else if(k==='f'||k==='F')full();\n  else if"
    "(k==='s'||k==='S')snap();});\nif(localStorage.getItem('ipcAuto')==='0')$('auto').checked=false"
    ";\n$('devurl').textContent=location.host;\nsetInterval(function(){if(!document.hidden)loadStat"
    "s();},2000);\nloadStatus();loadStats();loadList();startAuto();\n</script>\n</body>\n</html>\n";

/* 末尾那一个字节是 '\0'(C 自动加), 不占用上面的长度 */
