/**
 * @file    svc_http_page.c
 * @brief   回放页面的 HTML 源码(见 svc_http_page.h 的说明)
 *
 * 【模块职责】只放一段常量 HTML(带一点原生 JS);不含逻辑、不碰硬件
 * 【依赖方向】无
 * 【线程模型】只读常量
 * 【资源边界】约 4 KB 只读数据(.rodata)
 *
 * 编写约定(为了少转义、好维护):
 *   · HTML 属性与 JS 字符串**一律用单引号** ⇒ C 字符串里不用写 `\"`
 *   · 页面里出现 `%` 也没关系:它是用 `infra_tcp_write_all` 原样发出去的, 不走 printf
 */
#include "svc_http_page.h"

const char svc_http_page_html[] =
    "<!DOCTYPE html>\n"
    "<html lang='zh-CN'>\n"
    "<head>\n"
    "<meta charset='utf-8'>\n"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
    "<title>IPC 录像回放</title>\n"
    "<style>\n"
    " body{font-family:system-ui,'Microsoft YaHei',sans-serif;margin:0;"
    "background:#14181d;color:#e6e6e6}\n"
    " header{padding:10px 14px;background:#1b2027;border-bottom:1px solid #2b323b}\n"
    " h1{font-size:16px;margin:0;display:inline-block}\n"
    " #stat{color:#8b98a5;font-size:12px;margin-left:10px}\n"
    " #v{width:100%;max-height:60vh;background:#000;display:block}\n"
    " .bar{display:flex;height:26px;background:#1b2027;border-top:1px solid #2b323b;"
    "border-bottom:1px solid #2b323b}\n"
    " .blk{flex:1 1 0;min-width:3px;border-right:1px solid #14181d;cursor:pointer}\n"
    " .blk:hover{outline:1px solid #4da3ff;outline-offset:-2px}\n"
    " .blk.lock{background:#7a5a12}\n"
    " .blk.cur{background:#2f6fb5}\n"
    " .row{padding:8px 14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}\n"
    " button{background:#2b323b;color:#e6e6e6;border:1px solid #3a434e;"
    "border-radius:4px;padding:4px 10px;cursor:pointer}\n"
    " button:hover{background:#39424e}\n"
    " table{width:100%;border-collapse:collapse;font-size:13px}\n"
    " th,td{text-align:left;padding:4px 8px;border-bottom:1px solid #232a32}\n"
    " td.n{font-family:ui-monospace,Consolas,monospace}\n"
    " tr:hover{background:#1b2027}\n"
    " .note{color:#8b98a5;font-size:12px;padding:0 14px 16px}\n"
    " code{background:#1b2027;padding:1px 5px;border-radius:3px;color:#9fd0ff}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header><h1>IPC 录像回放</h1><span id='stat'>加载中…</span></header>\n"
    "<video id='v' controls playsinline preload='none'></video>\n"
    "<div class='bar' id='bar' title='时间轴:每一格是一段录像,橙色=已锁定'></div>\n"
    "<div class='row'>\n"
    "  <button onclick='load()'>刷新列表</button>\n"
    "  <button onclick='playNewest()'>播最新一段</button>\n"
    "  <span id='cur' class='n'></span>\n"
    "</div>\n"
    "<table><thead><tr><th>时间</th><th>大小</th><th>状态</th>"
    "<th>操作</th></tr></thead><tbody id='tb'></tbody></table>\n"
    "<p class='note'>直播(RTSP)浏览器播不了, 用 VLC 打开:"
    " <code id='rtsp'></code><br>\n"
    "连续回放整段录像(VLC/mpv): <code id='m3u'></code><br>\n"
    "页面直接调的就是设备的 REST 接口: <code>GET /recordings</code>、"
    "<code>GET /recordings/&lt;名&gt;</code>(支持 Range)、"
    "<code>PUT /recordings/&lt;名&gt;/lock</code>。</p>\n"
    "<script>\n"
    "var segs=[],cur='';\n"
    "function fmt(n){if(n>1048576)return (n/1048576).toFixed(1)+' MB';"
    "if(n>1024)return (n/1024).toFixed(0)+' KB';return n+' B';}\n"
    "function esc(s){return s.replace(/[&<>]/g,function(c){"
    "return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});}\n"
    "async function load(){\n"
    "  var r=await fetch('/recordings',{cache:'no-store'});\n"
    "  var d=await r.json();segs=d.segments||[];\n"
    "  document.getElementById('stat').textContent=segs.length+' 段录像';\n"
    "  var tb=document.getElementById('tb');tb.innerHTML='';\n"
    "  var bar=document.getElementById('bar');bar.innerHTML='';\n"
    "  for(var i=0;i<segs.length;i++){\n"
    "    var s=segs[i];\n"
    "    var tr=document.createElement('tr');\n"
    "    tr.innerHTML=\"<td class='n'>\"+esc(s.name.replace('.mp4',''))+"
    "\"</td><td>\"+fmt(s.size)+\"</td><td>\"+(s.locked?'已锁定':'—')+"
    "\"</td><td><button>\"+(s.locked?'解锁':'锁定')+\"</button> \"+\n"
    "      \"<button>另存</button></td>\";\n"
    "    var bs=tr.getElementsByTagName('button');\n"
    "    bs[0].onclick=function(k){return function(){lock(k);};}(i);\n"
    "    bs[1].onclick=function(k){return function(){save(k);};}(i);\n"
    "    tr.onclick=function(k){return function(ev){if(ev.target.tagName!='BUTTON')"
    "play(k);};}(i);\n"
    "    tb.appendChild(tr);\n"
    "    var b=document.createElement('div');\n"
    "    b.className='blk'+(s.locked?' lock':'');\n"
    "    b.title=s.name;\n"
    "    b.onclick=function(k){return function(){play(k);};}(i);\n"
    "    bar.appendChild(b);\n"
    "  }\n"
    "  document.getElementById('rtsp').textContent="
    "'rtsp://'+location.hostname+':8554/live';\n"
    "  document.getElementById('m3u').textContent="
    "location.origin+'/playlist.m3u';\n"
    "}\n"
    "function play(i){var s=segs[i];if(!s)return;cur=s.uri;\n"
    "  document.getElementById('v').src=s.uri;\n"
    "  document.getElementById('cur').textContent=s.name;\n"
    "  var bs=document.querySelectorAll('.blk');\n"
    "  for(var k=0;k<bs.length;k++)bs[k].className='blk'+(segs[k].locked?' lock':'')+"
    "(k==i?' cur':'');}\n"
    "function playNewest(){if(segs.length)play(0);}\n"
    "async function lock(i){var s=segs[i];if(!s)return;\n"
    "  var on=s.locked?0:1;\n"
    "  await fetch(s.lock_uri,{method:'PUT',body:String(on)});\n"
    "  load();}\n"
    "function save(i){var s=segs[i];if(!s)return;\n"
    "  var a=document.createElement('a');a.href=s.uri;a.download=s.name;a.click();}\n"
    "load();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
