/**
 * @file    svc_http_page.c
 * @brief   回放页面的 HTML 源码(见 svc_http_page.h 的说明)
 *
 * 【模块职责】只放一段常量 HTML(带一点原生 JS);不含逻辑、不碰硬件
 * 【依赖方向】无
 * 【线程模型】只读常量
 * 【资源边界】约 7 KB 只读数据(.rodata)
 *
 * 编写约定(为了少转义、好维护):
 *   · HTML 属性与 JS 字符串**一律用单引号**;表格用 DOM API 拼(`textContent`),
 *     不用 `innerHTML` 拼字符串 ⇒ C 里几乎不用写 `\"`, 也没有 HTML 注入问题
 *   · 页面里出现 `%` 没关系:它是用 `infra_tcp_write_all` 原样发出去的, 不走 printf
 *
 * 页面做的事(全走已有接口, 一份协议都不新发明):
 *   · `GET /recordings`(支持 `?before=` 翻页) → 分段列表 + 时间轴(每格一段)
 *   · `GET /status`                             → **正在录的那一段**(它还没收尾, 列表里看不到)
 *   · `<video src=uri>`                         → 播放;拖进度条时浏览器自动发 `Range`
 *   · `PUT lock_uri`                            → 锁定 / 解锁
 *   · 每 5 秒自动刷新(用户不必手点"刷新";这也正是"看不到最新段"那次困惑的解药)
 */
#include "svc_http_page.h"

const char svc_http_page_html[] =
    "<!DOCTYPE html>\n"
    "<html lang='zh-CN'>\n"
    "<head>\n"
    "<meta charset='utf-8'>\n"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
    "<title>IPC 录像回放</title>\n"
    "<style>\n"
    " body{font-family:system-ui,'Microsoft YaHei',sans-serif;margin:0;"
    "background:#14181d;color:#e6e6e6}\n"
    " header{padding:10px 14px;background:#1b2027;border-bottom:1px solid #2b323b}\n"
    " h1{font-size:16px;margin:0 10px 0 0;display:inline-block}\n"
    " #stat{color:#8b98a5;font-size:12px}\n"
    " #err{display:none;margin:8px 14px;padding:8px;border-radius:4px;"
    "background:#3a1d1d;color:#ffb4b4;font-size:13px;white-space:pre-wrap}\n"
    " #rec{display:none;margin:0 14px 8px;padding:6px 10px;border-radius:4px;"
    "background:#2a2413;color:#ffd479;font-size:13px}\n"
    " #v{width:100%;max-height:60vh;background:#000;display:block}\n"
    " .bar{display:flex;height:26px;background:#1b2027;border-top:1px solid #2b323b;"
    "border-bottom:1px solid #2b323b}\n"
    " .blk{flex:1 1 0;min-width:3px;border-right:1px solid #14181d;cursor:pointer}\n"
    " .blk:hover{outline:1px solid #4da3ff;outline-offset:-2px}\n"
    " .blk.lock{background:#7a5a12}\n"
    " .blk.rec{background:#4a3a0a}\n"
    " .blk.cur{background:#2f6fb5}\n"
    " .row{padding:8px 14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}\n"
    " button{background:#2b323b;color:#e6e6e6;border:1px solid #3a434e;"
    "border-radius:4px;padding:4px 10px;cursor:pointer}\n"
    " button:hover{background:#39424e}\n"
    " table{width:100%;border-collapse:collapse;font-size:13px}\n"
    " th,td{text-align:left;padding:4px 8px;border-bottom:1px solid #232a32}\n"
    " td.n{font-family:ui-monospace,Consolas,monospace}\n"
    " tr:hover{background:#1b2027}\n"
    " .note{color:#8b98a5;font-size:12px;padding:0 14px 16px}\n"
    " code{background:#1b2027;padding:1px 5px;border-radius:3px;color:#9fd0ff}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header><h1>IPC 录像回放</h1><span id='stat'>加载中…</span></header>\n"
    "<div id='err'></div>\n"
    "<div id='rec'></div>\n"
    "<video id='v' controls playsinline preload='none'></video>\n"
    "<div class='bar' id='bar' title='时间轴:每格一段录像;橙色=已锁定,深黄=正在录'></div>\n"
    "<div class='row'>\n"
    "  <button id='bnew'>播最新一段</button>\n"
    "  <button id='brec'>看最新(把正在录的收尾)</button>\n"
    "  <button id='bmore'>加载更早</button>\n"
    "  <label><input type='checkbox' id='auto' checked> 每 5 秒自动刷新</label>\n"
    "  <span id='cur' class='n'></span>\n"
    "</div>\n"
    "<table><thead><tr><th>时间</th><th>大小</th><th>状态</th>"
    "<th>操作</th></tr></thead><tbody id='tb'></tbody></table>\n"
    "<p class='note'>直播(RTSP)浏览器播不了, 用 VLC 打开: <code id='rtsp'></code><br>\n"
    "连续回放整段录像(VLC/mpv): <code id='m3u'></code><br>\n"
    "页面用的就是设备的 REST 接口: <code>GET /recordings</code>(支持 "
    "<code>?limit=&amp;before=</code> 翻页)、<code>GET /status</code>、"
    "<code>GET /recordings/&lt;名&gt;</code>(支持 Range)、"
    "<code>PUT /recordings/&lt;名&gt;/lock</code>。</p>\n"
    "<p class='note'>\"看最新\"会把**正在录的那一段立刻收尾**(边界仍在关键帧上, 一帧不丢),"
    " 于是它马上变成可播的分段 —— 代价是**多一个分段**;刚开的段(< 20 秒)不会被切,"
    " 这时直接给你上一段。接口: <code>HEAD /recent.mp4</code>"
    "(应答头 <code>X-Recent-Clip</code> 告诉你拿到的是哪一段)。</p>\n"
    "<script>\n"
    "var segs=[],total=0,pages=1,reclen=0;\n"
    "function $(id){return document.getElementById(id);}\n"
    "function fmt(n){if(n>1048576)return (n/1048576).toFixed(1)+' MB';"
    "if(n>1024)return (n/1024).toFixed(0)+' KB';return n+' B';}\n"
    "function t9(name){return name.substr(11,8);}\n"
    "function hm(sec){var m=Math.floor(sec/60);"
    "return m>=60?Math.floor(m/60)+' 小时 '+(m%60)+' 分':m+' 分钟';}\n"
    "function fail(e){var d=$('err');d.style.display='block';"
    "d.textContent='出错了: '+e.message+'\\n(可能是板子上的服务没在跑, 或网络断了)';}\n"
    "async function api(p){var r=await fetch(p,{cache:'no-store'});"
    "if(!r.ok)throw new Error('HTTP '+r.status+' '+p);return r.json();}\n"
    "function mkBtn(text,fn){var b=document.createElement('button');"
    "b.textContent=text;b.onclick=function(ev){ev.stopPropagation();fn();};return b;}\n"
    "function addRow(i,rec){\n"
    "  var s=rec?null:segs[i];var tr=document.createElement('tr');\n"
    "  var t=[document.createElement('td'),document.createElement('td'),\n"
    "         document.createElement('td'),document.createElement('td')];\n"
    "  t[0].className='n';\n"
    "  t[0].textContent=t9(rec?rec.name:s.name);\n"
    "  t[1].textContent=fmt(rec?rec.bytes:s.size);\n"
    "  t[2].textContent=rec?'正在录(未收尾, 暂时不可播)':(s.locked?'已锁定':'—');\n"
    "  if(rec){t[2].style.color='#ffd479';}else{\n"
    "    t[3].appendChild(mkBtn(s.locked?'解锁':'锁定',function(){lock(i);}));\n"
    "    t[3].appendChild(document.createTextNode(' '));\n"
    "    t[3].appendChild(mkBtn('另存',function(){save(i);}));\n"
    "    tr.onclick=function(){play(i);};\n"
    "  }\n"
    "  for(var k=0;k<4;k++)tr.appendChild(t[k]);\n"
    "  $('tb').appendChild(tr);\n"
    "}\n"
    "function render(){\n"
    "  var tb=$('tb');tb.textContent='';var bar=$('bar');bar.textContent='';\n"
    "  $('stat').textContent='共 '+total+' 段, 已列出 '+segs.length+' 段';\n"
    "  if(reclen)addRow(-1,reclen);\n"
    "  for(var i=0;i<segs.length;i++){\n"
    "    addRow(i,null);\n"
    "    var b=document.createElement('div');\n"
    "    b.className='blk'+(segs[i].locked?' lock':'');b.title=t9(segs[i].name);\n"
    "    b.onclick=function(k){return function(){play(k);};}(i);\n"
    "    bar.appendChild(b);\n"
    "  }\n"
    "  if(reclen){var r=document.createElement('div');r.className='blk rec';\n"
    "    r.title='正在录: '+t9(reclen.name);bar.appendChild(r);}\n"
    "}\n"
    "async function loadList(){try{\n"
    "  var d=await api('/recordings');segs=d.segments||[];total=d.count||segs.length;\n"
    "  pages=1;$('err').style.display='none';render();\n"
    " }catch(e){fail(e);}}\n"
    "async function more(){try{\n"
    "  if(!segs.length)return;\n"
    "  var last=segs[segs.length-1].name;\n"
    "  var d=await api('/recordings?before='+encodeURIComponent(last));\n"
    "  if(!d.segments||!d.segments.length){$('stat').textContent+='(没有更早的了)';return;}\n"
    "  segs=segs.concat(d.segments);pages++;total=d.count||total;render();\n"
    " }catch(e){fail(e);}}\n"
    "async function loadStatus(){try{\n"
    "  var d=await api('/status');\n"
    "  if(d.recording){\n"
    "    reclen=d;\n"
    "    var grew=Math.max(0,Math.floor((Date.now()/1000)-d.started_at));\n"
    "    $('rec').style.display='block';\n"
    "    $('rec').textContent='● 正在录 '+t9(d.name)+' —— 已录 '+hm(grew)+\n"
    "      ', 已写 '+fmt(d.bytes)+'(这一段要等收尾后才会出现在上面的列表里)';\n"
    "  }else{reclen=0;$('rec').style.display='none';}\n"
    "  $('rtsp').textContent=d.live_rtsp||('rtsp://'+location.hostname+':8554/live');\n"
    "  $('m3u').textContent=location.origin+'/playlist.m3u';\n"
    " }catch(e){fail(e);}}\n"
    "function play(i){var s=segs[i];if(!s)return;$('v').src=s.uri;\n"
    "  $('cur').textContent=s.name;\n"
    "  var bs=document.querySelectorAll('.blk');\n"
    "  for(var k=0;k<bs.length&&k<segs.length;k++)"
    "bs[k].className='blk'+(segs[k].locked?' lock':'')+(k==i?' cur':'');}\n"
    "async function lock(i){try{var s=segs[i];if(!s)return;\n"
    "  await fetch(s.lock_uri,{method:'PUT',body:String(s.locked?0:1)});\n"
    "  await loadList();}catch(e){fail(e);}}\n"
    "function save(i){var s=segs[i];if(!s)return;var a=document.createElement('a');\n"
    "  a.href=s.uri;a.download=s.name;a.click();}\n"
    "async function recent(){try{\n"
    "  $('cur').textContent='正在请板子收尾当前段(通常 1 秒内)…';\n"
    "  var r=await fetch('/recent.mp4',{method:'HEAD',cache:'no-store'});\n"
    "  if(!r.ok)throw new Error('HTTP '+r.status+' /recent.mp4');\n"
    "  var n=r.headers.get('X-Recent-Clip');\n"
    "  if(!n)throw new Error('应答里没有 X-Recent-Clip');\n"
    "  $('err').style.display='none';\n"
    "  $('v').src='/recordings/'+encodeURIComponent(n);\n"
    "  $('cur').textContent=n+' (刚收尾, 可拖进度条)';\n"
    "  await tick();\n"
    " }catch(e){fail(e);}}\n"
    "async function tick(){await loadStatus();if(pages<=1)await loadList();else render();}\n"
    "function startAuto(){if(window._t)clearInterval(window._t);\n"
    "  if($('auto').checked)window._t=setInterval(tick,5000);}\n"
    "$('bnew').onclick=function(){play(0);};\n"
    "$('brec').onclick=function(){recent();};\n"
    "$('bmore').onclick=function(){more();};\n"
    "$('auto').onchange=function(){startAuto();};\n"
    "loadList();loadStatus();startAuto();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
